version: "3.7"

services:
    mongodb:
        image: mongo:4.0
        environment: 
            - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/db_user
            - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_pass
        volumes: 
            - ./db/:/data/db
        ports:
            - "28017:27017"
        command: mongod
        secrets:
            - db_user
            - db_pass
secrets:
    db_user:
        file: ./secrets/db_user
    db_pass:
        file: ./secrets/db_pass
    